---
- name: Dump All Variables
  import_playbook: dump-all-variables.yml
  tags: [ never, debug ]

- name: Update Local DNS
  import_playbook: update-local-dns.yml

- name: Mount additional data devices under /mnt/disks
  import_playbook: mount-additional-data-devices.yml

- name: Kubespray User
  import_playbook: kubespray-user.yml

- name: Install Kubespray
  import_playbook: install-kubespray.yml
