---
- name: Run Python script
  delegate_to: localhost
  shell: |
    {{ role_path }}/python/test_script.py --test-message "{{ test_msg }}"
  args:
    executable: /bin/bash
  register: result

- name: Show result
  debug: msg="{{ result }}"
